get:
  tags:
  - user
  summary: Create user
  description: This can only be done by the logged in user.
  operationId: examples.api.api.createUser
  produces:
  - application/json
  parameters:
  - in: body
    name: body
    description: Created user object
    required: false
    schema:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type:
            - "string"
            - "null"
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
        phone:
          type: string
        userStatus:
          type: integer
          format: int32
          description: User Status
  responses:
  "201":
    description: successful operation